version: 2

jobs:
    build:
        docker:
            - image: cimg/node:10.15.3

        steps:
            - run:
                name: Node Version Check
                command: node -v

            - run:
                name: NPM Version Check
                command: npm -v

            - checkout

            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}

            - run:
                name: NPM Install
                command: npm install

            - save_cache:
                key: dependency-cache
                paths:
                  - ~/.cache/npm

            - run: npm test

            - store_artifacts:
                path: coverage
                destination: $CIRCLE_ARTIFACTS
